# Generated by Django 2.2.3 on 2020-08-12 02:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20200805_1436'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-created_time'], 'verbose_name': '文章post', 'verbose_name_plural': '文章post'},
        ),
    ]
